number of params: 39826962
Start training
Traceback (most recent call last):
  File "/home/ailab/anaconda3/envs/deformable_detr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ailab/anaconda3/envs/deformable_detr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/ailab/dungpt/sfa-detr/train.py", line 372, in <module>
    main(args)
  File "/workspace/ailab/dungpt/sfa-detr/train.py", line 306, in main
    model, criterion, data_loader_train, optimizer, device, epoch, args.clip_max_norm, args.print_feq)
  File "/workspace/ailab/dungpt/sfa-detr/engine.py", line 47, in train_one_epoch
    outputs, sfa_loss = model(samples)
  File "/home/ailab/anaconda3/envs/deformable_detr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/ailab/dungpt/sfa-detr/models/deformable_detr.py", line 209, in forward
    srcs, masks, pos, query_embeds)
  File "/home/ailab/anaconda3/envs/deformable_detr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/ailab/dungpt/sfa-detr/models/deformable_transformer.py", line 153, in forward
    memory = self.encoder(src_flatten, spatial_shapes, level_start_index, valid_ratios, lvl_pos_embed_flatten, mask_flatten)
  File "/home/ailab/anaconda3/envs/deformable_detr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/ailab/dungpt/sfa-detr/models/deformable_transformer.py", line 256, in forward
    output = layer(output, pos, reference_points, spatial_shapes, level_start_index, padding_mask)
  File "/home/ailab/anaconda3/envs/deformable_detr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/ailab/dungpt/sfa-detr/models/deformable_transformer.py", line 221, in forward
    src2 = self.self_attn(self.with_pos_embed(src, pos), reference_points, src, spatial_shapes, level_start_index, padding_mask)
  File "/home/ailab/anaconda3/envs/deformable_detr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/ailab/dungpt/sfa-detr/models/ops/modules/ms_deform_attn.py", line 122, in forward
    offset_normalizer[None, None, None, :, None, :]
RuntimeError: CUDA out of memory. Tried to allocate 80.00 MiB (GPU 0; 10.91 GiB total capacity; 9.90 GiB already allocated; 51.44 MiB free; 10.04 GiB reserved in total by PyTorch)